---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: getourneau/alpine-bash-git
inputs:
  - name: repo
    #  - name: repo-release
  - name: repo-dev
outputs:
  - name: out
run:
  path: /bin/bash
  args:
  - repo/ci/tasks/repo-dev.sh
