---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: java
    tag: 8-jdk-alpine    
inputs:
  - name: repo
  - name: m2
run:
  path: sh
  args:
    - repo/ci/tasks/unit.sh
